changelog:
  exclude:
    labels:
      - duplicate
      - invalid
      - wontfix
  categories:
    - title: Enhancements
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Dependencies
      labels:
        - dependencies
        - github_actions
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
